### ISSUE TITLE
No results after running setupTarAmpAnalysis

### ISSUE THREAD

**Issue by dcastaneda5** [bailey-lab/SeekDeep#8]
Hi!
I am currently trying to run this software to see the number of haplotypes I get across 20 samples that have been demultiplexed in the past. For this, I am running setupTarAmpAnalysis after I create my primer file, my sample file, and input everything else that is needed:

idFile:
```
target  forward reverse
pfmsp2  ATGAAGGTAATTAAAACATTGTCTATTATA  CTTTGTTACCATCGGTACATTCTT
pfmsp1  CTAGAAGCTTTAGAAGATGCAGTATTG     CTTAAATAGTATTCTAATTCAAGTGGATCA

```
overlap_file:
```
target  status
pfmsp2  noOverlap
pfmsp1  noOverlap
```

sample_files:
```
pfmsp1  sample1 P01
pfmsp1  sample2 P02
pfmsp1  sample3 P03
pfmsp1  sample4 P04
pfmsp1  sample5 P05
pfmsp1  sample6 P06
pfmsp1  sample7 P07
pfmsp1  sample8 P08
pfmsp1  sample9 P09
pfmsp1  sample10 P10
pfmsp1  sample11 P11
pfmsp1  sample12 P12
pfmsp1  sample13 P13
pfmsp1  sample14 P14
pfmsp1  sample15 P15
pfmsp1  sample16 P16
pfmsp1  sample17 P17
pfmsp1  sample18 P18
pfmsp1  sample19 P19
pfmsp1  sample20 P20
pfmsp2  sample1 P01
pfmsp2  sample2 P02
pfmsp2  sample3 P03
pfmsp2  sample4 P04
pfmsp2  sample5 P05
pfmsp2  sample6 P06
pfmsp2  sample7 P07
pfmsp2  sample8 P08
pfmsp2  sample9 P09
pfmsp2  sample10 P10
pfmsp2  sample11 P11
pfmsp2  sample12 P12
pfmsp2  sample13 P13
pfmsp2  sample14 P14
pfmsp2  sample15 P15
pfmsp2  sample16 P16
pfmsp2  sample17 P17
pfmsp2  sample18 P18
pfmsp2  sample19 P19
pfmsp2  sample20 P20

```
However, my results are completely empty, and when I looked at one of the files I saw this:

```
inputName       Total   failedBarcode   failedPrimers   mismatchedPrimers       mismatchedPrimersDimers failedOverlapPairProcessing     failedStatusPairProcessing      possibleContamination   filteredOff     used
P01     61009   0(0%)   61009(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P02     67360   0(0%)   67360(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P03     91549   0(0%)   91549(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P04     59636   0(0%)   59636(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P05     90535   0(0%)   90535(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P06     73735   0(0%)   73735(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P07     111794  0(0%)   111794(100%)    0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P08     66295   0(0%)   66295(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P09     60155   0(0%)   60155(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P10     81936   0(0%)   81936(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P11     66523   0(0%)   66523(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P12     66135   0(0%)   66135(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P13     81328   0(0%)   81328(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P14     51229   0(0%)   51229(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P15     52643   0(0%)   52643(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P16     55910   0(0%)   55910(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P17     44192   0(0%)   44192(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P18     35733   0(0%)   35733(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P19     66557   0(0%)   66557(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
P20     67929   0(0%)   67929(100%)     0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)
```

Could there be a problem with the primers I used for sequencing my data? I know that my data came demultiplexed already. If the primers were removed, is there any way that seekdeep could provide me with haplotype frequency without primers in my sequence data? Or could I manually add them by mapping my reads to references using samtools and then feed it back to seekdeep?

Thanks in advance for the help,

Daniel

**Comment by JeffAndBailey** [comment]
Hi Daniel,

To better help: can you describe your exact experimental approach in 
terms of amplification, library and sequencing.   Also, have you 
examined some of your reads for the primers do you know for sure that 
they were trimmed off previously?  Also, can you provide the settings 
you are using when you run SeekDeep itself.

Best,JB

**Comment by dcastaneda5** [comment]
Sure,
I have 15 patients and 5 cultured malaria samples for my data. The patients have been previously diagnosed with malaria. Then, we extracted the DNA and did a PCR on two length polymorphic gene markers (msp1 and msp2). We used Nextera during our library preparation step to randomly shear our amplicons. After this we did 2x250 bp in paired-end mode MiSeq sequencing and the data was given demultiplexed from the sequencing centre. When I noticed that I was getting no results, I decided to look if the primers were trimmed off by the sequencing centre, and as I feared, they were. When I looked for the PCR primers we used to amplify msp1 and msp2, I only found 2 reads that matched the primer sequence across my data. After this, I decided to map my reads to my msp1 and msp2 fasta references, so I could extract the mapped .fastq files of each one of them. Then, I added the primer sequence for the forward and reverse reads so I could simulate as if my primers were still there (I added both the sequence and the sequence quality to be the same set of 'letters'). Finally, I ran:

`SeekDeep setupTarAmpAnalysis --samples sampleNames.tab.txt --outDir output --inputDir fastq_trimmed --idFile ../idFile.tab.txt --overlapStatusFnp overlapStatuses.txt `

Then I ran:
`./runAnalysis.sh`

Followed by:
`./startServerCmd.sh`

And once I looked at the website with the proper address I saw my tabs empty. Nevertheless, after I added these 'simulated' primers, I noticed that my output was not exactly the same as the one I just posted:

```
inputName       Total   failedBarcode   failedPrimers   mismatchedPrimers       mismatchedPrimersDimers failedOverlapPairProcessing     failedStatusPairProcessing      possibleContamination   filteredOff     used
P01     48819   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   44800(91.8%)    0(0%)   2400(4.92%)     1619(3.32%)
P02     60738   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   56530(93.1%)    0(0%)   2348(3.87%)     1860(3.06%)
P03     67526   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   60767(90%)      0(0%)   3848(5.7%)      2911(4.31%)
P04     51553   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   46617(90.4%)    0(0%)   2372(4.6%)      2564(4.97%)
P05     64966   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   58300(89.7%)    0(0%)   4293(6.61%)     2373(3.65%)
P06     60914   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   55617(91.3%)    0(0%)   3376(5.54%)     1921(3.15%)
P07     94899   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   86907(91.6%)    0(0%)   4799(5.06%)     3193(3.36%)
P08     53291   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   46834(87.9%)    0(0%)   3383(6.35%)     3074(5.77%)
P09     46240   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   40326(87.2%)    0(0%)   3177(6.87%)     2737(5.92%)
P10     64166   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   58381(91%)      0(0%)   3360(5.24%)     2425(3.78%)
P11     53603   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   48811(91.1%)    0(0%)   2598(4.85%)     2194(4.09%)
P12     56897   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   48985(86.1%)    0(0%)   3965(6.97%)     3947(6.94%)
P13     68202   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   61124(89.6%)    0(0%)   3444(5.05%)     3634(5.33%)
P14     43508   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   35686(82%)      0(0%)   3733(8.58%)     4089(9.4%)
P15     30873   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   271(0.878%)     0(0%)   7003(22.7%)     23599(76.4%)
P16     49061   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   45181(92.1%)    0(0%)   1931(3.94%)     1949(3.97%)
P17     39487   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   35796(90.7%)    0(0%)   1421(3.6%)      2270(5.75%)
P18     27821   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   25898(93.1%)    0(0%)   1073(3.86%)     850(3.06%)
P19     58502   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   53977(92.3%)    0(0%)   2208(3.77%)     2317(3.96%)
P20     56506   0(0%)   0(0%)   0(0%)   0(0%)   0(0%)   52207(92.4%)    0(0%)   2465(4.36%)     1834(3.25%)


```

**Comment by JeffAndBailey** [comment]
Hi,

So, if you used tagmentation then you made random breaks in your msp1 
and msp2 PCR products to create library fragments and your begin and 
ends will be random within the product and unlikely to contain the 
primer let alone the entire length.   SeekDeep wasn't designed for 
"shotgun" and really won't work for tagmented libraries.  It was 
designed from defined sequencing from the product start and end so you 
will always traverse the primers at the beginning of the read because 
you are always starting sequencing from the same spot just 5' from the 
primer. I think probably by adding the primers on artificially you may 
be actually placing the primers at random positions from the perspective 
of your PCR product.  So, your output if you do manage to get some may 
have artifacts due to seekdeep expecting defined begin and ends and teh 
full length product for clustering.  It may call additional haplotypes 
that are simply differences in start and stop positions.  I frankly 
wouldn't recommend using SeekDeep. In terms of what you should use that 
depends on what you want to do? call variants? define COI and 
haplotypes?  You could map to the reference genome, but that may fail do 
to the repetitive nature or msp1 and msp2 and if you are getting 
fragments then you would need to predict the number of haplotypes.   if 
you want to predict the haplotypes you might try something like Spades, 
a local assembler,--there may be some newer software out there for this 
that I am unaware of.

I'm looping in the author of SeekDeep Nick Hathaway, as he may have and 
idea of how to trick out SeekDeep. Or, he may have made unadvertised 
modifications that can handle tagmented products. Nick will have to 
explain with failedStatusPRocess means.  I'm guessing that few % of 
fragments getting through may if from various postions in the product 
not align to each other well during the qluster step.  But, again, I 
would suggest finding some other software, but curious what nick might 
suggest.

Best, Jeff

**Comment by dcastaneda5** [comment]
Hi Jeff,

Sorry for the late reply. Thanks for the update and detailed explanation you gave. I was thinking to try a program, like shoRAH to run haplotype reconstruction based on random sequence reads produced from Nextera instead. Yes, the goal of my project is to define haplotype frequencies and therefore COI per sample. I will try spades, and maybe shoRAH. I read one of your papers where you compared SeekDeep against other software including this one. Thanks a lot for your help,

Daniel

**Comment by JeffAndBailey** [comment]
OK.  Shorah was a challenge if I remember although it may have been 
updated, one of which was that it requires all the reads to align to a 
reference--it didn't adjust the alignments.  Spades would  be a better 
bet most likely.
