### ISSUE TITLE
--processed

### ISSUE THREAD

**Issue by nikosdarzentas** [bailey-lab/SeekDeep#9]
Hello Nick,
I've been trying SeekDeep the last few days to see if it can help us in our antigen receptor sequence analysis, since it has some potentially very useful features. But I have some questions / issues, which I'll lay down separately.

First question is how this works, i.e. what's the suffix? An example would be great.
> --processed	Processed, Input Sequence Name has a suffix that contains abundance info

Many thanks in advance,
I'll be back with more :-)

**Comment by nickjhathaway** [comment]
So the suffix can be HapSeq.01_[NUMBER] or HapSeq.01_t[NUMBER] where NUMBER is the abundance information e.g. 

HapSeq.01_10 
or
HapSeq.01_t10

These above would say there are 10 of these sequences rather than just 1. 

Let me know if that helps.  

Nick

**Comment by nikosdarzentas** [comment]
Ah yes, I've seen "_t10" in the output - thank you.
